PROG               =	rm

MKC_CHECK_FUNCS1 =	undelete:unistd.h
MKC_REQUIRE_FUNCLIBS +=	fts_open:fts

MKC_REQUIRE_FUNCLIBS +=	fts_open:fts

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/mkc_imp.f_pwdgrp.mk"
.include "../mk/mkc_imp.f_strmode.mk"
.include "../mk/mkc_imp.f_arc4random.mk"

.include "../mk/addlinks.mk"
