PROG=	chmod

MKC_REQUIRE_FUNCLIBS =	fts_open:fts

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/mkc_imp.f_getsetmode.mk"
.include "../mk/mkc_imp.f_lchmod.mk"

.include "../mk/addlinks.mk"
