PROG =	chmod
MAN  =	chmod.1

MKC_REQUIRE_FUNCLIBS +=	fts_open:fts

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/imp.f_getsetmode.mk"
.include "../mk/imp.f_lchmod.mk"

.include "../mk/addlinks.mk"
