PROG =	pr
SRCS =	pr.c egetopt.c

COPTS.pr.c += -Wno-format-nonliteral

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/mkc_imp.f_raise_default_signal.mk"

.include "../mk/addlinks.mk"
