=head1 NAME

nbase - NetBSD userlevel portable to other UNIX-like systems

=head1 DESCRIPTION

nbase is a collection of NetBSD tools portable to Linux, MacOS-X and
other UNIX-like systems. Its version looks like x.y.z.n, where x is a
NetBSD major version, y -- NetBSD minor version, z -- NetBSD patch
level, and n -- nbase release number. For example, 7.0.0.4 means
fourth release of nbase that corresponds to NetBSD 7.0-RELEASE.

=head1 WWW

L<git repository|https://github.com/cheusov/nbase>

=head1 AUTHOR

2015-2017 (C) Aleksey Cheusov <vle@gmx.net> or <cheusov@netbsd.org>
