LIB   =	ndigest

SRCS =	keccak.c md5c.c md5hl.c rmd160.c rmd160hl.c sha1.c sha1hl.c        \
	sha2.c sha2hl.c sha3.c sha3hl.c tiger.c whirlpool.c md5.h rmd160.h \
	sha1.h sha2.h sha3.h tiger.h whirlpool.h

CPPFLAGS +=	-I.

.include <mkc.mk>
