PROG=	mv

MKC_CHECK_FUNCS2 +=	fcpxattr:sys/extattr.h

.include <mkc.init.mk>

.include "../mk/mkc_imp.f_pwdgrp.mk"
.include "../mk/mkc_imp.f_strmode.mk"
.include "../mk/mkc_imp.f_struct_stat.mk"
.include "../mk/mkc_imp.f_types.mk"

.include "../mk/addlinks.mk"
