PROG =	timeout

.include <mkc.init.mk>

CFLAGS.warns.gcc.4   += -Wno-error=return-type
CFLAGS.warns.clang.4 += -Wno-error=return-type

.include "../mk/hacks.mk"
.include "../mk/mkc_imp.f_sys_signame.mk"
.include "../mk/mkc_imp.f_macro.mk"

.include "../mk/addlinks.mk"
