PROG =	timeout
MAN  =	timeout.1

.include <mkc.init.mk>

CFLAGS.check   += -Wno-error=return-type

.include "../mk/hacks.mk"
.include "../mk/imp.f_sys_signame.mk"
.include "../mk/imp.f_macro.mk"

.include "../mk/addlinks.mk"
