#	$NetBSD: Makefile,v 1.11 2007/06/22 03:24:16 simonb Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG =		testcmd
PROGNAME ?=	test
SRCS =   	test.c
MAN =		test.1
LINKS =		${BINDIR}/test ${BINDIR}/[
MLINKS =	test.1 [.1

.include <mkc.mk>
