PROG =	ul
MAN  =	ul.1

CFLAGS.check +=		-erroff=E_STATEMENT_NOT_REACHED

MKC_REQD     +=		0.37.0

MKC_FEATURES +=		efun err

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/imp.f_curses.mk"

.include "../mk/addlinks.mk"
