PROG =	ul
MAN  =	ul.1

CFLAGS.check +=		-erroff=E_STATEMENT_NOT_REACHED

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/imp.f_curses.mk"
.include "../mk/imp.f_reallocarr.mk"

.include "../mk/addlinks.mk"
