PROG =	sort
SRCS =	append.c fields.c files.c fsort.c init.c msort.c sort.c tmp.c
SRCS +=	radix_sort.c

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/mkc_imp.f_efun.mk"

.include "../mk/addlinks.mk"
