# $NetBSD: Makefile,v 1.1 2009/08/15 16:21:04 joerg Exp $

PROG =	nbperf
SRCS =	nbperf.c
SRCS +=	nbperf-bdz.c nbperf-chm.c nbperf-chm3.c
SRCS +=	graph2.c graph3.c

MKC_CHECK_HEADERS = sys/endian.h endian.h

.include <mkc.prog.mk>
