PROG      =	qsubst
MAN       =	qsubst.1

WARNERR   =	no

MKC_FEATURES +=	progname

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/imp.f_curses.mk"
.include "../mk/imp.f_bsd_signal.mk"

.include "../mk/addlinks.mk"
