PROG =	du
MAN  =	du.1

MKC_REQUIRE_FUNCLIBS +=	fts_open:fts

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/imp.f_humanize_number.mk"
.include "../mk/imp.f_getbsize.mk"

.include "../mk/addlinks.mk"
