PROG =	du
MAN  =	du.1

MKC_REQUIRE_FUNCLIBS +=	fts_open:fts

MKC_FEATURES          =	humanize_number

.include <mkc.init.mk>

.include "../mk/hacks.mk"

.include "../mk/imp.f_getbsize.mk"

.include "../mk/addlinks.mk"
